print("this is my first line of code")
print("this code commiing form hitesh")
print("this code is from vineet")
print("This is basically our new changes by Hitesh in line number 4.")
print("this is a code done by vineet")
